### PR TITLE
Cmdliner.1.1.0

### PR DESCRIPTION
**Pull request by MisterDA**
Awaiting:
- https://github.com/ocurrent/obuilder/pull/100 ;
- updated Docker images.

### CODE REVIEW

**Review by talex5 — APPROVED** [review]
Thanks - looks good (once Dockerfiles are updated).

**Comment by MisterDA** [comment]
I've updated the dockerfiles and the obuilder submodule. I think this is good to go!

**Comment by punchagan** [comment]
Thanks for fixing this, @MisterDA !

**Comment by talex5** [comment]
CI says:
```
manifest for ocaml/opam:debian-11-ocaml-4.13@sha256:facb9f1272610683f75580a8189116dcc4f4fff6958640e81bf568ec8ffc6320 not found: manifest unknown: manifest unknown
```

**Pull request merged**
